[package]
name = "openrtb"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1.12", features = ["macros"] }
lambda_http = { version = "0.4.1" }
serde_json = "1.0"
rusoto_core = "0.47.0"
rusoto_kinesis = "0.47.0"
openssl = { version = "0.10", features = ["vendored"] }